- src/Config.cpp
Now we can run
```
opencc -c t2s -i input -o output
```
instead of
```
opencc -c t2s.json -i input -o output
```
with the builtin config files.
> Allow ext-less config filenames for package data.

- src/tools/CommandLine.cpp
This makes it more convenient for buffer editing with VIM or other editors.
> Do not output a trailing newline to the buffer.

- node/binding.cc
- package.json
iojs@3.0.0 requires nan@2.0.+ and g++-4.8
will fix installation failure on iojs@3.0.0
commit d6bf735f054d834dbb063bb4131261a9d92f555e
Author: Peter Cai <xqsx43cxy@126.com>
Date:   Fri Aug 14 20:24:28 2015 +0800
remove useless lines
commit 11928c1c83837bf66fa50e0a26ce591b0e8deeea
Author: Peter Cai <xqsx43cxy@126.com>
Date:   Fri Aug 14 17:34:10 2015 +0800
migrate to nan@2.0.0
and update mocha.
This fixes compatibility with iojs@3.0.0
Signed-off-by: Peter Cai <xqsx43cxy@126.com>
> node: fix compatibility with iojs@3.0.0

- Makefile
- README.md
Because of [System Integrity Protection](http://arstechnica.com/apple/2015/09/os-x-10-11-el-capitan-the-ars-technica-review/8/), root users cannot modify all files inside `/usr` directly on Mac OS 10.11. But we can still install opencc in `/usr/local`.
These changes make the build process more flexible to solve this problem, while leaving other systems unaffected.
> Update for Mac OS X El Capitan

- src/Config.cpp
- src/SerializableDict.hpp
- src/SimpleConverter.cpp
- src/UTF8Util.hpp
- src/opencc.h
(commit 1) How to build in VS2015 - Reference: http://www.cnblogs.com/lin277541/p/4928630.html
(commit 2) 系统是英文代码页，所以加了unicode文件名支持
顺便附上一个C#调用接口：
https://github.com/sgqy/mycolle/blob/master/mine/OpenCCEntry.cs
简单测试结果：
和1.0.1版的exe放在一起会被系统崩掉（管道正常，-i -o 参数异常）
和1.0.3版的exe放在一起正常工作
使用C#调用宽字符接口正常工作
---
Issue:
有关词典生成器出现的问题。
`SerializableDict.hpp`里的`TryLoadFromFile`接受一个UTF-8串，`SerializeToFile`接受一个ANSI串。
在ANSI编码环境里`TryLoadFromFile`的功能受限。
一种修改方向：`SerializeToFile`与打开文件时一样，统一接受UTF-8串，opencc_dict.exe加入字符转换过程。
这个动作修改较多，先等一等。
> (MSVC) Build in VS2015 (commit 1) and Unicode filename support (commit 2)

- src/Config.cpp
- src/ConfigTest.cpp
> Config::NewFromString throws the exception when path does not contain trailing slash

- README.md
Add a link to [SwiftyOpenCC](https://github.com/XQS6LB3A/SwiftyOpenCC), a simple, elegant way to use OpenCC on Apple devices.
> Add: Swift Framework

- .travis.yml
- README.md
- appveyor.yml
- package.json
- src/BinaryDict.cpp
- src/DartsDict.cpp
- src/TextDict.cpp
- 使用 `node-pre-gyp` #228
- 使用 [travis ci](https://travis-ci.org/gucong3000/OpenCC/builds/217117766) 来生成OS X和Linux下64位二进制包
- 使用 [appveyor](https://ci.appveyor.com/project/gucong3000/opencc/build/1.0.25) 来编译32位和64位windows下二进制包
- 使用`node-pre-gyp-github`将二进制包发布到[github releases](https://github.com/gucong3000/OpenCC/releases/tag/1.0.5)
- 解决Windows下编译失败的问题 #234
> prebuild on CI

- src/BinaryDict.cpp
- src/DartsDict.cpp
- src/TextDict.cpp
解决在Windows平台下使用node-gyp编译失败的问题
错误日志如下：
```shell
λ node-gyp build
gyp info it worked if it ends with ok
gyp info using node-gyp@3.5.0
gyp info using node@6.10.0 | win32 | x64
gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
binding.cc
win_delay_load_hook.cc
C:\open-source\OpenCC\src\BinaryDict.cpp(27): error C2589: “(”:“::”右边的非法标记 (编译源文件 ..\node\bindi
ng.cc) [C:\open
-source\OpenCC\build\binding.vcxproj]
C:\open-source\OpenCC\src\BinaryDict.cpp(27): error C2059: 语法错误:“::” (编译源文件 ..\node\binding.cc) [C:\
open-sourc
e\OpenCC\build\binding.vcxproj] …
```
> 解决node-gyp编译失败的错误

- README.md
Rime IME has moved to a new location on the internet. Its new home is at:
https://rime.im/
> update rimeime link  [ci skip]

- src/PhraseExtractTest.cpp
With gcc 8.2.0 on aarch64-linux-gnu, my build fails due to undefined INFINITY.  Including `<cmath>` corrects this.
Be aware, `<cmath>` is only guaranteed to supply INFINITY in C++11 or later (at least by my understanding).  gcc `<cmath>` supplies it with or without C++11 at least as far back as 4.3, but I don't know about other compilers.
> * include <cmath> to get INFINITY defined

- README.md
Since https protocol is supported, https should be used instead of http.
> doc(README.md): use https for online OpenCC

- data/config/t2hkp.json
- data/config/t2jp.json
`t2hkp.json`: Used in [sgalal/rime-cantonese](https://github.com/sgalal/rime-cantonese), related issue: https://github.com/sgalal/rime-cantonese/issues/7
`t2jp.json`: Used in [sgalal/rime-kunyomi](https://github.com/sgalal/rime-kunyomi)
Both of them are very useful configurations.
> Add missing configurations (t2hkp, t2jp)

- README.md
Even though the old packages.qa.debian.org is still available, recent development of Debian packages should be viewed using the new package tracker located at tracker.debian.org. This commit updates the link to Debian opencc package development tracker.
> README.md: Update link to Debian opencc package

- CMakeLists.txt
If I build OpenCC specifying `-DCMAKE_POLICY_DEFAULT_CMP0025=NEW` when invoking `cmake` (to enable [CMake policy 25](https://cmake.org/cmake/help/latest/policy/CMP0025.html) which makes a distinction between open-source Clang and Apple's Xcode Clang), then building with AppleClang fails because the build system does not recognize AppleClang and therefore does not add the required `-std=c++11` compiler flag:
```
$ cd /path/to/OpenCC/
$ mkdir -p build/rel
$ (cd build/rel; cmake -DCMAKE_POLICY_DEFAULT_CMP0025=NEW ../..)
-- The CXX compiler identification is AppleClang 9.1.0.9020039
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: …
```
> Also recognize AppleClang compiler ID

- python/setup.py
`keywords` field in `setup` function changed from `string` to `List<string>`
Fix https://github.com/BYVoid/OpenCC/issues/405
Reference https://docs.python.org/3/distutils/setupscript.html#additional-meta-data
> [Bugfix] setup.py syntax errors

- src/SimpleConverter.hpp
When I compile `ibus-libzhuyin` source code, after update `opencc` version with `gcc` v10.1.0,
I enconter this problem:
```
/usr/include/opencc/SimpleConverter.hpp:42:30: error: ‘string’ in namespace ‘std’ does not name a type
42 |   SimpleConverter(const std::string& configFileName);
|                              ^~~~~~
/usr/include/opencc/SimpleConverter.hpp:1:1: note: ‘std::string’ is defined in header ‘<string>’; did you forget to ‘#include <string>’?
+++ |+#include <string>
1 | /*
```
After adding `#include <string>` on the first line of `SimpleConverter.hpp` (The header file `ibus-libzhuyin` use), it seems the problem solved.
I'm not sure if there's same kind of problem exist in this source repository, just report this bug fyi.
Thanks!
> SimpleConverter.hpp: fix missing include of <string>

- src/Config.cpp
`configDirectory` may be empty, and accessing `back()` will make it crash
> fix access violation when configDirectory is empty

- .github/workflows/release-pypi.yml
Twine environments will now be exposed to the docker container.
> Fix docker twine environment variables

- src/DartsDict.cpp
- src/DartsDictTest.cpp
- src/MarisaDict.cpp
- src/MarisaDictTest.cpp
- src/TextDictTest.cpp
if query is longer than the longest word in dictionary.
> fix #523: {MarisaDict,DartsDict}::Match() does not check for exact match

- src/PhraseExtract.cpp
`src/PhraseExtract.cpp:104:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
`
> fix compiler warning

- README.md
#562: 添加 [opencc-extension](https://github.com/tnychn/opencc-extension) 到 README 中的 `Projects using OpenCC 使用 OpenCC 的項目` 部分
> Add link to opencc-extension in README

- README.md
- src/DictConverter.cpp
- src/DictConverter.hpp
This fixes a specific crash on Windows.
When `BUILD_SHARED_LIBS` is `ON` and CRT is statically linked (`/MT`), both libopencc (built as `opencc.dll`) and opencc_dict (built as `opencc_dict.exe`) contain separate CRT contexts.
https://github.com/BYVoid/OpenCC/blob/47d750462b4b057e7519b04ccfd4282409062f7c/src/tools/DictConverter.cpp#L48-L49
The call above allocates a new block for `inputArg._value`'s string content in `opencc_dict.exe` context.
https://github.com/BYVoid/OpenCC/blob/47d750462b4b057e7519b04ccfd4282409062f7c/src/DictConverter.cpp#L61-L68
At the end of `opencc::ConvertDictionary()` function, `inputFileName` (copied from `inputArg._value`) gets destroyed, its string content block (allocated by `opencc_dict.exe`) is freed in `opencc.dll` context. There will be an erroneous …
> For opencc::ConvertDictionary() parameters, pass references instead of values.

- .appveyor.yml
- .github/workflows/nodejs.yml
- release-pypi-linux.sh
- release-pypi-macos.sh
- release-pypi-windows.cmd
- Python 2.7 is EOL and will soon be removed from PyPI
- Node 10 is EOL and has already been removed from npm, meaning appveyor
no longer allows ANY new commits to be merged.
> Remove builds for Python 2.7 and node 10

- src/Lexicon.cpp
- src/Lexicon.hpp
- src/TextDict.cpp
Since the prohibition of duplicate keys in dicts is started from commit 3c33116694dd1bb938c0fe9ced11f23cc0beb719, the PR additionally adds the found duplicate key to output, which can help the migration of old config files.
The PR adds an optional arg `dupkey` to `Lexicon.IsUnique` to return the duplicate key, avoiding breaking existing code with best effort.
> Provide the duplicate key when Lexicon.IsUnique check fails

- .github/workflows/python.yml
- .github/workflows/release-pypi.yml
- .travis.yml
- CMakeLists.txt
- NEWS.md
- package.json
- release-pypi-linux.sh
- release-pypi-macos.sh
- release-pypi-windows.cmd
- setup.py
- Removal of Python 3.5, 3.6 and NodeJS 10
- Use ubuntu 18.04 instead of 16.04 for building and pushing to pypi
Fixes: https://github.com/BYVoid/OpenCC/issues/690
Fixes: https://github.com/BYVoid/OpenCC/issues/691
> Update version for 1.1.4 release + clean obsoletes

- setup.py
在使用 Apple M1 build wheel 時會因為錯誤的 `platform_tag` 導致建立出來的 `.whl`  無法安裝
這個 PR  讓 build 出來的 `.whl` 能夠被正確安裝。應該可以幫助到需要自行編譯套件的使用者(#565 )
> 測試目前自行編譯的版本可以運行在m1底下了
> Add support for apple silicon build tag

- .appveyor.yml
- .github/workflows/nodejs.yml
- .travis.yml
This should fix #731 and all those after
> Update node.js versions to 18 and drop the out-of-support 12 and 14

- CMakeLists.txt
- NEWS.md
- package-lock.json
- package.json
This should be ok for a new release supporting python 3.11, barring a translation of the messages in `NEWS.md`
> Release 1.1.5

- NEWS.md
- package-lock.json
- package.json
A new release is required so pypi won't break the release script for builds that didn't upload correctly
> Release 1.1.6

- CMakeLists.txt
cmake的官方文档：
https://cmake.org/cmake/help/latest/variable/CMAKE_BINARY_DIR.html
https://cmake.org/cmake/help/latest/variable/CMAKE_CURRENT_BINARY_DIR.html
这两个变量在顶级项目中是相同的，在子项目中应该用CMAKE_CURRENT_BINARY_DIR。
> 修复此项目作为子其他cmake项目的子项目时，导致install失败的问题

- CMakeLists.txt
- OpenCCConfig.cmake.in
- src/CMakeLists.txt
Currently OpenCC only has a pkg-config file, it's good for systems to locate standalone OpenCC package. But if a project using CMake that want to make OpenCC as its subproject / dependency, it will need to write a FindOpenCC.cmake to find package, which is a hassle to do so. And for Android platform, pkg-config is unavailable since NDK doesn't support it. So it's necessary to add support of CMake modules, then a project is able to just `find_package(OpenCC)` and `target_link_libraries(<project_library_name> OpenCC::OpenCC)` to add OpenCC as subproject / dependency.
> Add support of CMake config modules

- CMakeLists.txt
- src/CMakeLists.txt
In the commit a13ed0a6 (PR #763 ), some DIR_LIBRARY variable usages are modified to make install destination relative to be more portable, but this will break the original designed purpose of DIR_LIBRARY, so this commit will revert the changes.
> Fix broken DIR_LIBRARY usages

- CMakeLists.txt
- OpenCCConfig.cmake.in
Ref: https://cmake.org/cmake/help/latest/module/CMakePackageConfigHelpers.html
> Set missing OPENCC_INCLUDE_DIR for CMake config modules

- .appveyor.yml
- .github/workflows/nodejs.yml
- .github/workflows/python.yml
- .github/workflows/release-pypi.yml
- .travis.yml
- package-lock.json
- release-pypi-linux.sh
- release-pypi-macos.sh
- release-pypi-windows.cmd
Fixes https://github.com/BYVoid/OpenCC/issues/819
> Add support for py3.12, node20, remove EOL py3.7, node16

- release-pypi-linux.sh
- setup.py
Update the platform name from manylinux1 to manylinux2014 in the Linux build scripts and setup.py to comply with the updated Python wheel specification. This change ensures that the built packages are compatible with the newer manylinux2014 standard, which provides better support for newer Linux distributions and wheel formats.
> build: Update to `manylinux2014` in build scripts and setup.py (#874)

- .npmignore
npm install opencc
...
npm ERR!   python: can't open file 'C:\\souce code\\dbmigrate\\node_modules\\opencc\\data\\scripts\\reverse.py': [Errno 2] No such file or directory
...
The following is my environment:
Node v20.11.1
Npm 10.2.4
Windows 11
Visual C++ 2022
Python 3.11.6
> fix errors when build is required during "npm install opencc"

- README.md
> Rename `longbridgeapp` to `longbridge`.

- CMakeLists.txt
- README.md
macOS is no longer called Mac OS X or any other variations, and do not refer to macOS the OS as Mac the hardware.
> Unify macOS naming

- CMakeLists.txt
Use CMake reserved variable to specify default C++ language version,
so version can be adjust later by each target accordingly.
Recently I noticed that we can not change the C++ language version for targets
through `target_compile_features`. It turns out that setting language version
with `add_definitions` is incompatible with `target_compile_features`, as
the definition flags got propagated to actual command unconditionally.
This PR try to set the language version in a way that CMake awares.
see also:
- https://cmake.org/cmake/help/latest/variable/CMAKE_CXX_STANDARD.html
> Set default language version through variable

- node/dicts.gypi
By default, the command will be `python3`. On Windows, it will use `python.exe`.
> Fix "python" command in gyp.

- src/Segments.hpp
Template base class `std::iterator` is deprecated in C++ 17, we can just define the type alias explicitly.
> Fix deprecated declarations in C++17
